config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  root to: "posts#index"

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}
       delete '/shared_user_delete' => "posts#shared_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :shared_users, dependent: :destroy
	belongs_to :user
	validates :title, :body, :presence => true 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, :except => [:show, :index]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @users = params[:post][:share].reject(&:empty?)
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
    @users.each do |user|
         @share = SharedUser.create(:user_id => user, :post_id => @post.id)
    end  
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if params[:post][:share].present?
        @users = params[:post][:share].reject(&:empty?) 
        @users.each do |user|
             @share = SharedUser.create(:user_id => user, :post_id => @post.id)
        end 
    end    
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
#    @post = Post.find_by_id(params[:id])
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
  end

  def shared_user
     @share = SharedUser.find(params[:format])
     @share.destroy
      redirect_back(fallback_location: root_path)   
  end



    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body,:user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-md-3">
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body,class:"form-control"  %>
  </div>

  <% if (@post.user_id == nil) %>
    <div class="field">
      <%= form.label :share_with %>
      <%= form.collection_select :share, User.where.not(id: current_user.id), :id, :email, {}, :multiple => 'true',class:"form-select form-select-lg mb-3"%>
  <%end%>
  <% if (@post.user_id == current_user.id)%>
      <%= form.label :share_with %>
      <% @post.shared_users.each do |su| %>
      <table>
         <tr><td> <%= su.user.email%></td>
          <td><%= link_to 'Delete', shared_user_delete_path(su.id), method: :delete,class:"btn btn-danger btn-sm float-right",style:'color:white' %> </td>
        </tr>
      </table>  
      <% end%>
      <% remaining_users = User.where.not(id: current_user.id).where.not(id:@post.shared_users.pluck(:user_id))%>
      <%= form.collection_select :share, remaining_users, :id, :email, {}, :multiple => 'true',class:"form-select form-select-lg mb-3"%>
    </div>
  <%end%>
  <div class="actions">
    <%= form.submit "Submit",class:"btn btn-success" ,onClick:"window.location.reload()"%>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path,class:"btn btn-link" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
  <% if current_user.superadmin_role?%>
    <h1>Welcome Admin!</h1>
  <% end %>

<%= link_to 'New Post', new_post_path ,class:"btn btn-success",style:'color:white'%>
<br>

    <% @posts.each do |post| %>
    <br>
    <div class="border border-light rounded">
      <% if (current_user.id == post.user_id) || (post.shared_users.where(:user_id => current_user.id).present? ) %>  
         <br>
        <h2><%= post.title %></h2>by<h6><%= post.user.email%></h6>
        <p><%= post.body %></p>
        <div><%= link_to 'Edit', edit_post_path(post),class:"btn btn-primary btn-sm float-right",style:'color:white' %>
          <% if (post.user_id == current_user.id) %>
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-sm float-right",style:'color:white' %>
          <%end%>
        </div>  
      <% end%>
    </div>    
    <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path,class:"btn btn-link" %>

app/views/posts/shared_user.html.erb
<p id="notice"><%= notice %></p>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', posts_path,class:"btn btn-link" %>