config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  root to: "posts#index"

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}
       delete '/shared_user_delete' => "posts#shared_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseAdminApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>




<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "PMS" , root_path, class:"navbar-brand" %>              
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home" , root_path, class:"nav-link active" %>          
        </li>
        <% if current_user.present?%>
          <% if current_user.superadmin_role?  || current_user.supervisor_role? %>
          <li class="nav-item">        
            <%= link_to "Dashboard" ,rails_admin_path, class:"nav-link active" %>
         </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav float-right">
      <% if !current_user.nil? %>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, class:"nav-link active" , method: :delete do %>Log out<% end %>
                <div style="color: white">  
                    <%= current_user.email %>
                </div>
              </li> 
      <% else%>
            <li class="nav-item">
              <%= link_to "Sign Up/Login" , new_user_session_path, class:"nav-link active" %>          
            </li>                 
      <% end %>        
      </ul>      
    </div>
  </div>
</nav>

    <div class="container-fluid">
        <%= yield %>
    </div>    
  </body>
</html>